# Generated by Django 5.0.6 on 2026-06-20 20:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('code', models.CharField(help_text='用于报表汇总, 建议英文/数字', max_length=20, unique=True, verbose_name='分类编码')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='商品唯一标识, 如 P0001', max_length=50, unique=True, verbose_name='SKU 编号')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('specification', models.CharField(blank=True, help_text='如 "1.5L 红色"', max_length=100, verbose_name='规格型号')),
                ('unit', models.CharField(choices=[('件', '件'), ('套', '套'), ('箱', '箱'), ('千克', '千克'), ('米', '米'), ('台', '台'), ('个', '个')], default='件', max_length=10, verbose_name='计量单位')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='单价(元)')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='成本价(元)')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='当前库存')),
                ('safety_stock', models.IntegerField(default=10, help_text='低于此值视为库存不足, 看板会高亮提醒', verbose_name='安全库存警戒线')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品图片')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='在用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['sku'],
                'indexes': [models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'), models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx')],
            },
        ),
    ]
