# Generated by Django 4.2.30 on 2026-06-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='用于扫码入库, 需全局唯一, 如 EAN-13 / 自定义编码', max_length=64, null=True, unique=True, verbose_name='条形码'),
        ),
    ]
