# Generated by Django 5.0.6 on 2026-06-20 20:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_stock', models.IntegerField(verbose_name='系统库存')),
                ('actual_stock', models.IntegerField(verbose_name='实际盘点库存')),
                ('difference', models.IntegerField(editable=False, verbose_name='差异')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='盘点时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_checks', to=settings.AUTH_USER_MODEL, verbose_name='盘点人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_checks', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '盘点记录',
                'verbose_name_plural': '盘点记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InOutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('inbound', '入库'), ('outbound', '出库')], max_length=10, verbose_name='类型')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='本次出入库单价, 用于成本/销售统计', max_digits=10, verbose_name='单价(元)')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inout_records', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inout_records', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '出入库流水',
                'verbose_name_plural': '出入库流水',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', 'created_at'], name='inventory_i_type_17b1b1_idx'), models.Index(fields=['product'], name='inventory_i_product_a8197b_idx')],
            },
        ),
    ]
